#!/bin/bash
setxkbmap -option && setxkbmap -layout us -variant intl -option ctrl:swapcaps -print >~/.config/niri/keymap.xkb
setxkbmap -option && setxkbmap -layout us -variant intl -option ctrl:swapcaps
