#!/bin/bash

FILE=/tmp/display_mirror
if test -f "$FILE"; then
    echo "$FILE exist"
    xrandr --output eDP-1 --auto --mode 1920x1080 --output HDMI-1 --same-as eDP-1 
    rm -rf $FILE
else
    if (xrandr | grep "HDMI-1 disconnected"); then
         xrandr --output eDP-1 --auto --mode 1920x1080 --output HDMI-1 --off 
    else
         xrandr --output eDP-1 --auto --left-of HDMI-1 --mode 1920x1080 --output HDMI-1 --auto --mode 1920x1080 --primary

    fi
fi
