#!/bin/bash

FILE=/tmp/display_mirror
if test -f "$FILE"; then
    echo "$FILE exist"
    xrandr --output eDP1 --auto --mode 1920x1080 --output HDMI1 --same-as eDP-1 
    rm -rf $FILE
else
    if (xrandr | grep "HDMI1 disconnected"); then
         xrandr --output eDP1 --auto --mode 1920x1080 --output HDMI1 --off 
    else
         xrandr --output eDP1 --auto --left-of HDMI1 --mode 1920x1080 --output HDMI1 --auto --mode 1920x1080 --rate 120 --primary --output DP2 --auto --mode 1920x1080 --right-of HDMI1 --rate 60

    fi
fi
